import type { Metadata } from "next";
import "./globals.css";
import { cafe24Font } from "./assets/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${cafe24Font.variable} antialiased min-h-screen bg-gradient-to-r from-rose-100 via-rose-50 to-rose-200`}
      >
        {children}
      </body>
    </html>
  );
}
